### ISSUE TITLE
an error with _variables.scss 

### ISSUE THREAD

**Issue by achavazza** [tguelcan/generator-bootstrap-theme#1]
after run `yo bootstrap-theme` the generator doesn't copy the last `_variables.scss` from node_modules, to the project

when you run npm run dev, the `_variables.scss` file in the project doesn't have the last variables added by the Bootstrap Team, therefore the console list some errors, and doesn't run.

Can you please fix this? (i dont know how to do it myself)

BTW.: the project link in the yeoman repository its wrong

**Comment by tguelcan** [comment]
i released an update. now everything should work. You can customize the variables.scss as you like.
